// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using patrickLearn.Data;

#nullable disable

namespace patrickLearn.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("patrickLearn.Models.Chilldren", b =>
                {
                    b.Property<int>("ChilldrenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime");

                    b.Property<string>("ChilldImageUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("HusbandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WifeId")
                        .HasColumnType("int");

                    b.HasKey("ChilldrenId");

                    b.HasIndex("HusbandId");

                    b.HasIndex("WifeId");

                    b.ToTable("Chilldren");
                });

            modelBuilder.Entity("patrickLearn.Models.Husband", b =>
                {
                    b.Property<int>("HusbandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HusbandImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("HusbandId");

                    b.ToTable("husbands");
                });

            modelBuilder.Entity("patrickLearn.Models.Wife", b =>
                {
                    b.Property<int>("WifeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HusbandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WifeImageUrl")
                        .HasColumnType("longtext");

                    b.HasKey("WifeId");

                    b.HasIndex("HusbandId");

                    b.ToTable("Wife");
                });

            modelBuilder.Entity("patrickLearn.Models.Chilldren", b =>
                {
                    b.HasOne("patrickLearn.Models.Husband", "husband")
                        .WithMany("chilldrens")
                        .HasForeignKey("HusbandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("patrickLearn.Models.Wife", "wife")
                        .WithMany("chilldrens")
                        .HasForeignKey("WifeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("husband");

                    b.Navigation("wife");
                });

            modelBuilder.Entity("patrickLearn.Models.Wife", b =>
                {
                    b.HasOne("patrickLearn.Models.Husband", "husband")
                        .WithMany("wives")
                        .HasForeignKey("HusbandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("husband");
                });

            modelBuilder.Entity("patrickLearn.Models.Husband", b =>
                {
                    b.Navigation("chilldrens");

                    b.Navigation("wives");
                });

            modelBuilder.Entity("patrickLearn.Models.Wife", b =>
                {
                    b.Navigation("chilldrens");
                });
#pragma warning restore 612, 618
        }
    }
}
